<a href="https://colab.research.google.com/github/Mimohamed1998/power_opt_simulation/blob/main/matrix_based_implementation_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Customer Configurations

In [ ]:
customer_cap  = 2
l_status = 3

# Create the dummay dataframe

In [ ]:
import numpy as np

In [ ]:
import pandas as pd
import random

# Constants
NUM_WINGS = 50
MIN_ROOMS_PER_WING = 135
MAX_ROOMS_PER_WING = 150
NORMAL_ROOMS = 8
LUXURY_ROOMS = 2

# Function to generate random luxury status and energy cost
def generate_luxury_status():
    luxury_status = random.choice([1,2,3])
    if luxury_status == 1:
        return luxury_status, random.randint(70, 100)
    elif luxury_status == 2:
        return luxury_status, random.randint(90, 120)
    else:
        return luxury_status, random.randint(110, 130)

# Initialize lists for DataFrame columns
room_numbers = []
per_room_energy_costs = []
wing_numbers = []
luxury_statuses = []
room_capacities = []

# Create DataFrame
for wing in range(NUM_WINGS):
    wing_rooms = random.randint(MIN_ROOMS_PER_WING, MAX_ROOMS_PER_WING)
    for room in range(1, wing_rooms + 1):
        room_number = room
        luxury_status, energy_cost = generate_luxury_status()
        room_capacity = random.choice([2, 3])

        room_numbers.append(room_number)
        per_room_energy_costs.append(energy_cost)
        wing_numbers.append(chr(ord('A') + wing))
        luxury_statuses.append(luxury_status)
        room_capacities.append(room_capacity)

# Create DataFrame
data = {
    'Room_Number': room_numbers,
    'Per_Room_Energy_Cost': per_room_energy_costs,
    'Wing_Number': wing_numbers,
    'Luxury_Status': luxury_statuses,
    'Room_Capacity': room_capacities
}

hotel_df = pd.DataFrame(data)

# Display the DataFrame
print(hotel_df)


      Room_Number  Per_Room_Energy_Cost Wing_Number  Luxury_Status  \
0               1                    95           A              1   
1               2                   114           A              2   
2               3                    98           A              2   
3               4                   111           A              2   
4               5                    78           A              1   
...           ...                   ...         ...            ...   
7136          136                   107           r              2   
7137          137                   115           r              3   
7138          138                   123           r              3   
7139          139                    81           r              1   
7140          140                   113           r              3   

      Room_Capacity  
0                 2  
1                 3  
2                 2  
3                 3  
4                 3  
...             ...  
7136 

## Testing the dataframe

In [ ]:
hotel_df[hotel_df['Room_Number']==1]

Room_Number  Per_Room_Energy_Cost Wing_Number  Luxury_Status  \
0               1                    95           A              1   
136             1                   102           B              2   
285             1                    93           C              2   
430             1                   106           D              2   
572             1                    97           E              1   
708             1                    95           F              2   
846             1                   127           G              3   
988             1                   108           H              2   
1131            1                    99           I              2   
1273            1                   122           J              3   
1419            1                   118           K              3   
1567            1                    82           L              1   
1714            1                    81           M              1   
1859            1                   122           N              3   
2009            1                    86           O              1   
2150            1                    96           P              1   
2294            1                    79           Q              1   
2438            1                   107           R              2   
2578            1                   128           S              3   
2720            1                   124           T              3   
2861            1                    71           U              1   
3006            1                   109           V              2   
3155            1                   120           W              3   
3304            1                   110           X              3   
3448            1                    97           Y              2   
3584            1                    90           Z              2   
3726            1                   130           [              3   
3872            1                    86           \              1   
4008            1                   130           ]              3   
4149            1                   113           ^              2   
4291            1                    83           _              1   
4430            1                    97           `              2   
4580            1                   125           a              3   
4720            1                    72           b              1   
4864            1                   101           c              2   
5012            1                   118           d              2   
5152            1                   122           e              3   
5299            1                   130           f              3   
5437            1                   112           g              3   
5581            1                   123           h              3   
5729            1                    73           i              1   
5864            1                    90           j              2   
6004            1                    94           k              2   
6146            1                    98           l              2   
6294            1                   112           m              3   
6440            1                   106           n              2   
6578            1                    92           o              2   
6715            1                   130           p              3   
6858            1                   105           q              2   
7001            1                   116           r              3   

      Room_Capacity  
0                 2  
136               2  
285               2  
430               2  
572               3  
708               2  
846               2  
988               2  
1131              3  
1273              2  
1419              2  
1567              3  
1714              2  
1859              3  
2009              2  
2150              3  
2294              2  
2438              3  
2578             

In [ ]:
hotel_df[hotel_df['Wing_Number']=='B'].count()

Room_Number             149
Per_Room_Energy_Cost    149
Wing_Number             149
Luxury_Status           149
Room_Capacity           149
dtype: int64

In [ ]:
hotel_df[hotel_df['Room_Capacity']==2].count()

Room_Number             3561
Per_Room_Energy_Cost    3561
Wing_Number             3561
Luxury_Status           3561
Room_Capacity           3561
dtype: int64

## Create the wing datafrma

In [ ]:
import pandas as pd
import random

# Constants
NUM_WINGS = 50
MIN_WING_COST = 300
MAX_WING_COST = 350

# Initialize lists for DataFrame columns
wing_numbers = []
wing_costs = []

# Create DataFrame for wing information
for wing in range(NUM_WINGS):
    wing_number = chr(ord('A') + wing)
    wing_cost = random.uniform(MIN_WING_COST, MAX_WING_COST)

    wing_numbers.append(wing_number)
    wing_costs.append(wing_cost)

# Create DataFrame
wing_data = {
    'Wing_Number': wing_numbers,
    'Wing_Cost': wing_costs
}

wing_df = pd.DataFrame(wing_data)

# Display the DataFrame
print(wing_df)


   Wing_Number   Wing_Cost
0            A  322.044007
1            B  319.010817
2            C  337.259507
3            D  330.365833
4            E  345.732697
5            F  344.828325
6            G  338.698340
7            H  336.469137
8            I  300.475097
9            J  339.704904
10           K  330.251831
11           L  306.799199
12           M  348.059053
13           N  316.235579
14           O  306.423130
15           P  305.508389
16           Q  319.171466
17           R  343.941799
18           S  325.441240
19           T  340.003996
20           U  302.024042
21           V  317.855414
22           W  311.283585
23           X  321.933253
24           Y  329.594636
25           Z  324.446303
26           [  328.439958
27           \  321.275120
28           ]  323.510580
29           ^  301.636710
30           _  301.799841
31           `  347.941320
32           a  332.799262
33           b  324.395945
34           c  311.242774
35           d  316.857266
3

# pre process metric

In [ ]:
hotel_df['status'] = True

In [ ]:
# Find wing with the highest number of rooms
wing_max_rooms = hotel_df.groupby('Wing_Number')['Room_Number'].count().max()
wing_max_rooms

150

In [ ]:
# Create DataFrame with rows from 0 to max_rooms_per_wing
rooms_df = pd.DataFrame({'Room_Number': range(wing_max_rooms )})
rooms_df['Room_Number'] = rooms_df['Room_Number']+1

In [ ]:
cross_joined_df = pd.merge(wing_df[['Wing_Number']].assign(key=1), rooms_df.assign(key=1), on='key').drop('key', axis=1)

cross_joined_df

Wing_Number  Room_Number
0              A            1
1              A            2
2              A            3
3              A            4
4              A            5
...          ...          ...
7495           r          146
7496           r          147
7497           r          148
7498           r          149
7499           r          150

[7500 rows x 2 columns]

In [ ]:
# Perform left join with cross_joined_df and fill subset with 65,535
hotel_df_processed = pd.merge(cross_joined_df, hotel_df, on=['Wing_Number', 'Room_Number'], how='left')
# hotel_df_processed['Per_Room Energy_Cost'] = hotel_df_processed['Per_Room_Energy_Cost'].fillna(65535)
hotel_df_processed['Luxury_Status'] = hotel_df_processed['Luxury_Status'].fillna(0)
hotel_df_processed['Room_Capacity'] = hotel_df_processed['Room_Capacity'].fillna(0)
hotel_df_processed['status'] = hotel_df_processed['status'].fillna(False)

# hotel_df_processed = hotel_df_processed.sort('Room Number')

# Display the resulting hotel DataFrame
print("\nHotel DataFrame:")
hotel_df_processed


Hotel DataFrame:


Wing_Number  Room_Number  Per_Room_Energy_Cost  Luxury_Status  \
0              A            1                  95.0            1.0   
1              A            2                 114.0            2.0   
2              A            3                  98.0            2.0   
3              A            4                 111.0            2.0   
4              A            5                  78.0            1.0   
...          ...          ...                   ...            ...   
7495           r          146                   NaN            0.0   
7496           r          147                   NaN            0.0   
7497           r          148                   NaN            0.0   
7498           r          149                   NaN            0.0   
7499           r          150                   NaN            0.0   

      Room_Capacity  status  
0               2.0    True  
1               3.0    True  
2               2.0    True  
3               3.0    True  
4               3.0    True  
...             ...     ...  
7495            0.0   False  
7496            0.0   False  
7497            0.0   False  
7498            0.0   False  
7499            0.0   False  

[7500 rows x 6 columns]

In [ ]:
# Sort the DataFrame by 'Wing Number' and 'Room Number'
hotel_df_processed = hotel_df_processed.sort_values(by=['Wing_Number', 'Room_Number'])
hotel_df_processed

Wing_Number  Room_Number  Per_Room_Energy_Cost  Luxury_Status  \
0              A            1                  95.0            1.0   
1              A            2                 114.0            2.0   
2              A            3                  98.0            2.0   
3              A            4                 111.0            2.0   
4              A            5                  78.0            1.0   
...          ...          ...                   ...            ...   
7495           r          146                   NaN            0.0   
7496           r          147                   NaN            0.0   
7497           r          148                   NaN            0.0   
7498           r          149                   NaN            0.0   
7499           r          150                   NaN            0.0   

      Room_Capacity  status  
0               2.0    True  
1               3.0    True  
2               2.0    True  
3               3.0    True  
4               3.0    True  
...             ...     ...  
7495            0.0   False  
7496            0.0   False  
7497            0.0   False  
7498            0.0   False  
7499            0.0   False  

[7500 rows x 6 columns]

# Creating the wing cost

# Create the initial metrices

0. Room ID metric

1. capacity metric

2. per room cost metric

3. wing cost

4. luxury status

In [ ]:
# Room id metrics

room_id_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Room_Number'].apply(list))
room_id_metric = np.array(room_id_metric, dtype="float32")
room_id_metric

array([[  1.,   2.,   3., ..., 148., 149., 150.],
       [  1.,   2.,   3., ..., 148., 149., 150.],
       [  1.,   2.,   3., ..., 148., 149., 150.],
       ...,
       [  1.,   2.,   3., ..., 148., 149., 150.],
       [  1.,   2.,   3., ..., 148., 149., 150.],
       [  1.,   2.,   3., ..., 148., 149., 150.]], dtype=float32)

In [ ]:
# Room capacity metric

room_capacity_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Room_Capacity'].apply(list))
room_capacity_metric = np.array(room_capacity_metric, dtype="float32")
room_capacity_metric

array([[2., 3., 2., ..., 0., 0., 0.],
       [2., 2., 2., ..., 2., 2., 0.],
       [2., 3., 3., ..., 0., 0., 0.],
       ...,
       [2., 2., 2., ..., 0., 0., 0.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 2., 2., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
# per room cost metric

room_energy_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Per_Room_Energy_Cost'].apply(list))
room_energy_metric = np.array(room_energy_metric, dtype="float32")
room_energy_metric

array([[ 95., 114.,  98., ...,  nan,  nan,  nan],
       [102.,  96., 104., ..., 113.,  79.,  nan],
       [ 93.,  76., 114., ...,  nan,  nan,  nan],
       ...,
       [130.,  77., 113., ...,  nan,  nan,  nan],
       [105., 101., 108., ...,  nan,  nan,  nan],
       [116.,  95.,  84., ...,  nan,  nan,  nan]], dtype=float32)

In [ ]:
wing_df

Wing_Number   Wing_Cost
0            A  322.044007
1            B  319.010817
2            C  337.259507
3            D  330.365833
4            E  345.732697
5            F  344.828325
6            G  338.698340
7            H  336.469137
8            I  300.475097
9            J  339.704904
10           K  330.251831
11           L  306.799199
12           M  348.059053
13           N  316.235579
14           O  306.423130
15           P  305.508389
16           Q  319.171466
17           R  343.941799
18           S  325.441240
19           T  340.003996
20           U  302.024042
21           V  317.855414
22           W  311.283585
23           X  321.933253
24           Y  329.594636
25           Z  324.446303
26           [  328.439958
27           \  321.275120
28           ]  323.510580
29           ^  301.636710
30           _  301.799841
31           `  347.941320
32           a  332.799262
33           b  324.395945
34           c  311.242774
35           d  316.857266
36           e  309.676688
37           f  341.410186
38           g  340.965297
39           h  301.118353
40           i  323.909329
41           j  331.199327
42           k  329.860930
43           l  346.348286
44           m  323.294244
45           n  331.568239
46           o  300.686816
47           p  340.203898
48           q  320.950407
49           r  334.765104

In [ ]:
# per room cost metric

room_wing_cost_metric = np.stack(wing_df.groupby('Wing_Number')['Wing_Cost'].apply(list))
room_wing_cost_metric = np.array(room_wing_cost_metric , dtype="float32")
room_wing_cost_metric

array([[322.044  ],
       [319.0108 ],
       [337.25952],
       [330.36584],
       [345.7327 ],
       [344.82834],
       [338.69833],
       [336.46915],
       [300.4751 ],
       [339.7049 ],
       [330.25183],
       [306.7992 ],
       [348.05905],
       [316.23557],
       [306.42313],
       [305.5084 ],
       [319.17148],
       [343.9418 ],
       [325.44125],
       [340.004  ],
       [302.02405],
       [317.8554 ],
       [311.2836 ],
       [321.93326],
       [329.59464],
       [324.4463 ],
       [328.43997],
       [321.27512],
       [323.5106 ],
       [301.63672],
       [301.79984],
       [347.9413 ],
       [332.79926],
       [324.39594],
       [311.24277],
       [316.85727],
       [309.6767 ],
       [341.4102 ],
       [340.9653 ],
       [301.11835],
       [323.90933],
       [331.19934],
       [329.86093],
       [346.3483 ],
       [323.29425],
       [331.56824],
       [300.68683],
       [340.2039 ],
       [320.9504 ],
       [334.7651 ]],

In [ ]:
# luxury status

# per room cost metric

room_lux_metric = np.stack(hotel_df_processed.groupby('Wing_Number')['Luxury_Status'].apply(list))
room_lux_metric = np.array(room_lux_metric, dtype="float32")
room_lux_metric

array([[1., 2., 2., ..., 0., 0., 0.],
       [2., 2., 2., ..., 3., 1., 0.],
       [2., 1., 2., ..., 0., 0., 0.],
       ...,
       [3., 1., 2., ..., 0., 0., 0.],
       [2., 2., 2., ..., 0., 0., 0.],
       [3., 1., 1., ..., 0., 0., 0.]], dtype=float32)

## Get the room and wing occupancies

In [ ]:
room_capacity_metric.shape[0]

50

In [ ]:
import numpy as np

# Create room_occupancy matrix
room_occupancy = np.zeros(room_capacity_metric.shape, dtype=int)

# Set the first row to be full of ones
room_occupancy[0, :] = 1

# Set the second to third rows with a mix of 1s and 0s
room_occupancy[1:room_capacity_metric.shape[0]-3, :] = np.random.choice([0, 1], size=(46, room_capacity_metric.shape[1]))

# Set the last row to be full of zeros
room_occupancy[room_capacity_metric.shape[0]-1, :] = 0

# Create wing_occupancy matrix as binary
wing_occupancy_binary = np.any(room_occupancy, axis=1).astype(int)

# Display the matrices
print("Room Occupancy Matrix:")
print(room_occupancy)

print("\nWing Occupancy Matrix:")
print(wing_occupancy_binary)


Room Occupancy Matrix:
[[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Wing Occupancy Matrix:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0]


## Processing the metrices

In [ ]:
room_occupancy[:7,]

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

In [ ]:
room_occupancy.shape

(50, 150)

In [ ]:
customer_cap
l_status
customer_cap

2

### making binary metrices

In [ ]:
room_capacity_metric

array([[2., 3., 2., ..., 0., 0., 0.],
       [2., 2., 2., ..., 2., 2., 0.],
       [2., 3., 3., ..., 0., 0., 0.],
       ...,
       [2., 2., 2., ..., 0., 0., 0.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 2., 2., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
# Capacity processing
print('initlal room_capacity_metric')
print(room_capacity_metric)
room_capacity_metric_pr = np.where(room_capacity_metric >= customer_cap, 1, 0)
print('processed room_capacity_metric')
print(room_capacity_metric_pr)

initlal room_capacity_metric
[[2. 3. 2. ... 0. 0. 0.]
 [2. 2. 2. ... 2. 2. 0.]
 [2. 3. 3. ... 0. 0. 0.]
 ...
 [2. 2. 2. ... 0. 0. 0.]
 [3. 2. 3. ... 0. 0. 0.]
 [3. 2. 2. ... 0. 0. 0.]]
processed room_capacity_metric
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]]


In [ ]:
# Luxury processing
print('initlal room_lux_metric')
print(room_lux_metric)
room_lux_metric_pr = np.where(room_lux_metric >= l_status, 1, 0)
print('processed room_capacity_metric')
print(room_lux_metric_pr)

initlal room_lux_metric
[[1. 2. 2. ... 0. 0. 0.]
 [2. 2. 2. ... 3. 1. 0.]
 [2. 1. 2. ... 0. 0. 0.]
 ...
 [3. 1. 2. ... 0. 0. 0.]
 [2. 2. 2. ... 0. 0. 0.]
 [3. 1. 1. ... 0. 0. 0.]]
processed room_capacity_metric
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


### Inverting metrics

In [ ]:
# Room occupancy

print('before_inverting')
print(room_occupancy)
room_occupancy_inv = ~room_occupancy.astype(bool)
room_occupancy_inv = room_occupancy_inv.astype(int)
print('after_inverting')
print(room_occupancy_inv)

before_inverting
[[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
after_inverting
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [ ]:
# wing occupancy

print('before_inverting')
print(wing_occupancy_binary)
wing_occupancy_binary_inv = ~wing_occupancy_binary.astype(bool)
wing_occupancy_binary_inv = wing_occupancy_binary_inv.astype(int)
print('after_inverting')
print(wing_occupancy_binary_inv)

before_inverting
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0]
after_inverting
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 1]


### Defining the room cost

In [ ]:
print(room_capacity_metric_pr.shape)
print(room_energy_metric.shape)
print(room_lux_metric_pr.shape)
print(room_occupancy_inv.shape)

(50, 150)
(50, 150)
(50, 150)
(50, 150)


In [ ]:
room_energy_metric

array([[ 95., 114.,  98., ...,  nan,  nan,  nan],
       [102.,  96., 104., ..., 113.,  79.,  nan],
       [ 93.,  76., 114., ...,  nan,  nan,  nan],
       ...,
       [130.,  77., 113., ...,  nan,  nan,  nan],
       [105., 101., 108., ...,  nan,  nan,  nan],
       [116.,  95.,  84., ...,  nan,  nan,  nan]], dtype=float32)

In [ ]:
cost_of_rooms = (
    room_capacity_metric_pr
    *room_energy_metric
    *room_lux_metric_pr
    *room_occupancy_inv
    )
cost_of_rooms

array([[  0.,   0.,   0., ...,  nan,  nan,  nan],
       [  0.,   0.,   0., ...,   0.,   0.,  nan],
       [  0.,   0.,   0., ...,  nan,  nan,  nan],
       ...,
       [130.,   0.,   0., ...,  nan,  nan,  nan],
       [  0.,   0.,   0., ...,  nan,  nan,  nan],
       [116.,   0.,   0., ...,  nan,  nan,  nan]])

In [ ]:

cost_of_wings = (

       wing_occupancy_binary_inv.reshape(NUM_WINGS,1)
       *  room_wing_cost_metric
)

cost_of_wings

array([[  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0

In [ ]:
cost_of_wings_pr = np.tile(cost_of_wings, (1, room_capacity_metric.shape[1]))
cost_of_wings_pr

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [340.20388794, 340.20388794, 340.20388794, ..., 340.20388794,
        340.20388794, 340.20388794],
       [320.95040894, 320.95040894, 320.95040894, ..., 320.95040894,
        320.95040894, 320.95040894],
       [334.7651062 , 334.7651062 , 334.7651062 , ..., 334.7651062 ,
        334.7651062 , 334.7651062 ]])

In [ ]:
final_cost_per_room = cost_of_rooms+cost_of_wings_pr
final_cost_per_room

array([[  0.        ,   0.        ,   0.        , ...,          nan,
                 nan,          nan],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,          nan],
       [  0.        ,   0.        ,   0.        , ...,          nan,
                 nan,          nan],
       ...,
       [470.20388794, 340.20388794, 340.20388794, ...,          nan,
                 nan,          nan],
       [320.95040894, 320.95040894, 320.95040894, ...,          nan,
                 nan,          nan],
       [450.7651062 , 334.7651062 , 334.7651062 , ...,          nan,
                 nan,          nan]])

In [ ]:

flattened_array = final_cost_per_room.flatten()
non_zero_non_nan_indices = np.where(np.logical_and(flattened_array != 0, ~np.isnan(flattened_array)))

# Get the indices of the first 3 lowest values after excluding 0 and NaN
sorted_indices = np.argsort(flattened_array[non_zero_non_nan_indices])[:1]

# Convert the flattened indices to the original 2D indices
row_indices, col_indices = np.unravel_index(non_zero_non_nan_indices[0][sorted_indices], final_cost_per_room.shape)

# Get the values and positions
lowest_values = flattened_array[non_zero_non_nan_indices][sorted_indices]
positions = list(zip(row_indices, col_indices))

# Display the original array, flattened array, and result
print("Original Array:")
print(final_cost_per_room)


print("\nIndices of First 3 Lowest Values (excluding 0 and NaN):")
print(positions)

print("\nValues of First 3 Lowest Values (excluding 0 and NaN):", lowest_values)

Original Array:
[[  0.           0.           0.         ...          nan          nan
           nan]
 [  0.           0.           0.         ...   0.           0.
           nan]
 [  0.           0.           0.         ...          nan          nan
           nan]
 ...
 [470.20388794 340.20388794 340.20388794 ...          nan          nan
           nan]
 [320.95040894 320.95040894 320.95040894 ...          nan          nan
           nan]
 [450.7651062  334.7651062  334.7651062  ...          nan          nan
           nan]]

Indices of First 3 Lowest Values (excluding 0 and NaN):
[(36, 86)]

Values of First 3 Lowest Values (excluding 0 and NaN): [110.]


In [ ]:
positions[0][1]

86

In [ ]:
best_wing =np.array( wing_df[['Wing_Number']].sort_values(by= ['Wing_Number']).reset_index(drop=True))[positions[0][0]][0]
best_wing

'e'

In [ ]:
best_room = positions[0][1]
best_room

86